name             'arma3'
maintainer       'AzTek Native Ltd.'
maintainer_email 'peter.green@aztek-native.com'
license          'All rights reserved'
description      'Installs/Configures arma3'
long_description 'Installs/Configures arma3'
version          '0.1.0'
depends          'steamcmd'
